pipeline {
   agent {
    kubernetes {
      inheritFrom "kube-agent"
    }
  }
 // environment {

 // }
  stages{
    stage("Build"){
      steps{
        container('maven'){
          // With tests passed build and package the app
          sh 'mvn -f app/pom.xml clean install'
        }
      }
    }
  }
}
