controller:
  serviceType: LoadBalancer
  
persistence:
  enabled: true
  existingClaim: jenkins-pv-claim
  storageClass: "local-storage"
  provisioner: "kubernetes.io/no-provisioner"
  volumeBindingMode: "WaitForFirstConsumer"
  accessMode: "ReadWriteOnce"
  size: "10Gi"
  pv:
    name: "jenkins-pv-volume"
    labels:
      type: local
    path: "/mnt"
    nodeAffinity:
      key: "kubernetes.io/hostname"
      value: "node1"
  pvc:
    name: "jenkins-pv-claim"
  annotations: {}
  labels: {}
  volumes:
  mounts:

agent:
  podTemplates:
    kube-agent: |
      - name: kube-agent
        label: jenkins-agent
        serviceAccount: jenkins
        namespace: jenkins
        inheritFrom: "default"
        containers:
          - name: maven
            image: maven:3.8.7-openjdk-18-slim
            command: "sleep"
            args: "99d"
            ttyEnabled: true
            resourceRequestCpu: "400m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "1024Mi"
          - name: podman
            image: quay.io/podman/stable
            command: "sleep"
            args: "99d"
            ttyEnabled: true
            privileged: true
            resourceRequestCpu: "400m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "1024Mi"
