controller:
  serviceType: LoadBalancer
  
persistence:
  enabled: true
  existingClaim: jenkins-pv-claim
  storageClass: "local-storage"
  provisioner: "kubernetes.io/no-provisioner"
  volumeBindingMode: "WaitForFirstConsumer"
  accessMode: "ReadWriteOnce"
  size: "10Gi"
  pv:
    name: "jenkins-pv-volume"
    labels:
      type: local
    path: "/mnt"
    nodeAffinity:
      key: "kubernetes.io/hostname"
      value: "192.168.60.26"
  pvc:
    name: "jenkins-pv-claim"
  annotations: {}
  labels: {}
  volumes:
  mounts:

agent:
  podTemplates:
    kube-agent: |
      - name: kube-agent
        label: jenkins-agent
        serviceAccount: jenkins
        namespace: jenkins
        inheritFrom: "default"
        initContainers:
        -  name: init-docker-config
           image: busybox
           command: ["/bin/sh", "-c"]
           args:
           - |
             echo '{
             "exec-opts": ["native.cgroupdriver=systemd"],
             "log-driver": "json-file",
             "log-opts": {
               "max-size": "100m"
             },
             "storage-driver": "overlay2",
             "insecure-registries":["192.168.49.2:32002"]
             }' > /etc/docker/daemon.json
           volumeMounts:
           - name: docker-config
             mountPath: /etc/docker
        containers:
          - name: maven
            image: maven:3.8.7-openjdk-18-slim
            command: "sleep"
            args: "99d"
            ttyEnabled: true
            resourceRequestCpu: "400m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "1024Mi"
          - name: docker
            image: docker:dind
            command:
            - dockerd
            - '--host=unix:///var/run/docker.sock'
            - '--host=tcp://0.0.0.0:2375'
            ttyEnabled: true
            privileged: true
            resourceRequestCpu: "400m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "1024Mi"
            volumeMounts:
            - name: docker-config
              mountPath: /etc/docker
        volumes:
        - name: docker-config
          hostPath:
            path: /etc/docker

